# -------------------------------------------------------------------
# An example to create DGF database.
#
# Author: Liang Ding
# Email: myliang.ding@mail.utoronto.ca
# -------------------------------------------------------------------

from seisdb.DDGF import DDGFdb

def create_DGF_database():
    '''
        Create the DGF database.
    '''

    dENZ_dirList = ['the *.bin files generated by using the force in the direction of E',
                    'the *.bin files generated by using the force in the direction of N',
                    'the *.bin files generated by using the force in the direction of Z']

    NSPEC = int('Refer to the 3D model')
    NGLL = int('Refer to the 3D model')
    model_dir = str('The directory to the 3D model files (such as the *ibool.bin)')

    # the index of slice, staring from 0
    idx_processor = 120    # user specified
    # the index of the first waveform field snapshot
    step0 = 0
    # the index of the last waveform field snapshot
    step1 = 18001
    # the step interval of the waveform field snapshot
    dstep = 50

    saving_dir = str('*/database/DGF/')
    # network name
    network = "CI"
    # station name
    station = 'VTV'
    # the time interval in second of the DGF database.
    dt = 0.5

    print("Working ... ")
    dgf = DDGFdb(NSPEC, NGLL, model_dir)
    dgf.create_db(dENZ_dirList, idx_processor, step0, step1, dstep, saving_dir, network, station, dt)


if __name__ == '__main__':
    create_DGF_database()


